import { Nav } from "@/components/nav/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div className="flex">
          <div>
            <Nav />
          </div>

          <div className="container mx-auto p-4">{props.children}</div>
        </div>
        {props.modal}
      </body>
    </html>
  );
}
